name: "publish"
on:
  push:
    branches:
      - main
      - swift-cpp-shell-rust-tauri-core # todo-zm: remove before merging

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
          - platform: macos-latest
            arch: aarch64-apple-darwin
          - platform: macos-13
            arch: x86_64-apple-darwin
          - platform: windows-latest
            arch: x86_64-pc-windows-msvc
          - platform: windows-11-arm
            arch: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          targets: ${{ matrix.arch }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # - name: Rust setup ${{ matrix.arch }}
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     targets: ${{ matrix.arch }}

      # - name: Rust cache
      #   uses: swatinem/rust-cache@v2
      #   with:
      #     workspaces: "./src-tauri -> target"

      # - uses: pnpm/action-setup@v3
      #   with:
      #     version: 8
      # - name: Sync node version and setup cache
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "lts/*"
      #     cache: "pnpm" # Set this to npm, yarn or pnpm.

      # - name: Install frontend dependencies
      #   # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
      #   run: pnpm install # Change this to npm, pnpm or pnpm.

      # - name: Build the app for ${{ matrix.arch }}
      #   uses: tauri-apps/tauri-action@dev
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      #     TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      #     APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      #     APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      #     APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      #     APPLE_ID: ${{ secrets.APPLE_ID }}
      #     APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      #     APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      #   with:
      #     tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
      #     releaseName: "v__VERSION__"
      #     releaseBody: "See the assets to download this version and install."
      #     releaseDraft: true
      #     prerelease: false
      #     # args: --verbose
      #     args: --target ${{ matrix.arch }}
